//package com.example.demo.model;
//
//import jakarta.persistence.*;
//import lombok.*;
//@Data
//@Entity
//@Table(name = "product_variants")
//
//public class ProductVariant {
//    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    private Integer id;
//
//    @Column(name = "prod_id", nullable = false)
//    private Integer prodId;
//    @Column(name="price")
//    private Integer price;
//    private Integer quantity;
//    private Double discount;
//
//    // Getters and Setters
//}
package com.example.demo.model;

import jakarta.persistence.*;
import lombok.*;

@Data
@Entity
@Table(name = "product_variants")
public class ProductVariant {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "prod_id", nullable = false)
    private Integer prodId; // Assuming this refers to a Product entity

    @Column(name = "price")
    private Integer price;

    @Column(name = "quantity")
    private Integer quantity;

    @Column(name = "discount")
    private Double discount;

    // Getters and Setters are generated by Lombok (@Data), so we don't need to manually define them
}
